#!/usr/bin/env python3
"""
Export the live SupplyMind tables from Postgres (POSTGRES_CONNECTION_STRING in .env)
to a single .sql file: TRUNCATE + INSERT for every row.

Usage (from repository root):
  py scripts/dump_supplymind_to_sql.py
  py scripts/dump_supplymind_to_sql.py path/to/out.sql

Requires: psycopg2-binary (see SupplyMindAI/requirements.txt)
"""
from __future__ import annotations

import sys
from datetime import date, datetime
from decimal import Decimal
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import psycopg2
from psycopg2.extras import RealDictCursor
from psycopg2.extensions import adapt

from db.supabase_client import get_connection_string

TABLES_ORDER = ["hubs", "shipments", "stops", "risks", "insights"]
ORDER_BY_CLAUSE = {
    "hubs": "hub_name",
    "shipments": "shipment_id",
    "stops": "shipment_id, stop_number",
    "risks": "risk_id",
    "insights": "insight_id",
}


def sql_literal(val) -> str:
    if val is None:
        return "NULL"
    if isinstance(val, datetime):
        return adapt(val).getquoted().decode("utf-8")
    if isinstance(val, date):
        return adapt(val).getquoted().decode("utf-8")
    if isinstance(val, Decimal):
        return str(val)
    if isinstance(val, float):
        return repr(val)
    if isinstance(val, int):
        return str(val)
    if isinstance(val, str):
        return adapt(val).getquoted().decode("utf-8")
    if isinstance(val, (bytes, memoryview)):
        return adapt(bytes(val)).getquoted().decode("utf-8")
    return adapt(str(val)).getquoted().decode("utf-8")


def main() -> int:
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "db" / "live_complete_dump.sql"
    out.parent.mkdir(parents=True, exist_ok=True)

    conn = psycopg2.connect(get_connection_string())
    try:
        lines = [
            "-- SupplyMind live export (schema unchanged; data only)",
            f"-- Generated by scripts/dump_supplymind_to_sql.py",
            "",
            "TRUNCATE insights, stops, risks, shipments, hubs CASCADE;",
            "",
        ]
        with conn.cursor(cursor_factory=RealDictCursor) as cur:
            for table in TABLES_ORDER:
                ob = ORDER_BY_CLAUSE[table]
                cur.execute(f"SELECT * FROM {table} ORDER BY {ob}")
                rows = cur.fetchall()
                if not rows:
                    lines.append(f"-- (no rows in {table})")
                    lines.append("")
                    continue
                cols = list(rows[0].keys())
                col_list = ", ".join(cols)
                lines.append(f"-- {table} ({len(rows)} rows)")
                for row in rows:
                    vals = ", ".join(sql_literal(row[c]) for c in cols)
                    lines.append(
                        f"INSERT INTO {table} ({col_list}) VALUES ({vals});"
                    )
                lines.append("")
        out.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"Wrote {out} ({out.stat().st_size} bytes)")
    finally:
        conn.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
